name: "Refresh database"
on:
  schedule:
    - cron: "0 18 * * *" # 5pm UTC = 6am NZT
  workflow_dispatch:
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size=2gb
        ports:
          - 4444:4444
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: pip install -r scripts/requirements.txt
      - name: Rebuild sqlite DB from govt.nz list
        run: python scripts/scrape_organisations.py
      - name: Generate CSV files from sqlite database
        run: ./scripts/convert_sqlite_to_csv.sh
      - name: Commit database changes
        run: |
          set -eux

          git config --local user.email "helper@utf9k.net"
          git config --local user.name "Helper Bot"

          if [ $(git diff --numstat --exit-code) -eq 0 ];
            # No changes have occurred so there's no point generating a commit"
            exit $exit_status
          fi
          
          git add .
          git commit -a -m "Dataset has been updated" || exit 0