name: "Refresh database"
on:
  schedule:
    - cron: "0 18 * * *" # 5pm UTC = 6am NZT
  workflow_dispatch:
env:
  PYTHONUNBUFFERED: 1 # ensure that python scripts live output instead of buffering

jobs:
  sync:
    name: Sync
    timeout-minutes: 30
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: pip install -r scripts/requirements.txt
      - name: Rebuild sqlite DB from govt.nz list
        run: python scripts/scrape_organisations.py
        env:
          BROWSERLESS_API_TOKEN: ${{ secrets.BROWSERLESS_API_TOKEN }}
          BROWSERLESS_URL: ${{ secrets.BROWSERLESS_URL }}
      - name: Generate CSV files from sqlite database
        run: ./scripts/convert_sqlite_to_csv.sh
      - name: Commit database changes
        run: |
          set -eux

          git config --local user.email "helper@utf9k.net"
          git config --local user.name "Helper Bot"

          if [ -z "$(git status --porcelain)" ]; then
            # No changes have occurred so there's no point generating a commit"
            exit 0
          fi
          
          git add .
          git commit -m "Dataset has been updated"
          git push